version: '3.8'

services:
  minecraft-smp:
    build: .
    container_name: minecraft-smp
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - ./data/world:/minecraft/world
      - ./data/plugins:/minecraft/plugins
      - ./data/logs:/minecraft/logs
      - ./data/eula.txt:/minecraft/eula.txt
      - ./data/server.properties:/minecraft/server.properties
    environment:
      - MEMORY_SIZE=2G
      - MINECRAFT_VERSION=1.21.1
    networks:
      - minecraft-network

networks:
  minecraft-network:
    driver: bridge